version: '3.1'
services:
  app:
    container_name: newbpm
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://dbpostgresql:5432/camunda
    image: newbpm
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - dbpostgresql
  dbpostgresql:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=camunda
      - POSTGRES_USER=camunda
      - POSTGRES_DB=camunda