spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://dbpostgresql:5432/camunda
    username: camunda
    password: camunda
    hikari:
      connection-timeout: 5000
      maximum-pool-size: 10
      validation-timeout: 2000
      leak-detection-threshold: 300000

camunda.bpm:
  admin-user:
    id: 1
    password: 1
  webapp:
    index-redirect-enabled: true

